### ISSUE TITLE
setAutoLogin.sh: "unlucky passwords"

### ISSUE THREAD

**Issue by FrancoisCapon** [brunerd/macAdminTools#2]
Hi, 

For a CTF, I study how `kcpassword` are encrypted and decrypted.

So, I tested different tools and I tried some "unlucky passwords": 
* PARTY
* 12R3456789012R#5

Unlucky because some password character are "xored" with the same character in the key `}.R#Ò¼Ýê£¹.`, so the result is `x00` and some tools "dosen't like that".

With this script and PARTY, we have a warning
```
line 60: warning: command substitution: ignored null byte in input
```
and the character `R` xored with himself is missing
```
2dc8778bbcddeaa3b91f7d
2dc800778bbcddeaa3b91f7d
```

I tried something but I think that the only solution is to write the result directly to `/etc/kcpassword`, because:

> [You can't store a null byte in a string because Bash uses C-style strings, which reserve the null byte for terminators. So you need to rewrite your script to simply pipe the sequence that contains the null byte without Bash needing to store it in the middle.](https://unix.stackexchange.com/questions/347390/bash-cant-store-hexvalue-0x00-in-variable#answer-347409) 

```bash
$ echo -ne '\0' | xxd -p
00
$ printf '%b' '\0' | xxd -p
00
$ i=$(echo -ne '\0')
warning: command substitution: ignored null byte in input
$ i=$'\0'; echo -ne $i | xxd -p | wc -w
0
```

**Comment by brunerd** [comment]
Hey @FrancoisCapon - thank you so much for pointing this bit of "bad luck" out! The solution was to redirect the output to `/dev/stdout` and _never_ store the result in a string. I could have switched to zsh since it does allow nulls in strings but this required minimal changes and was a more fun exercise. So now folks can have a password PARTY 🥳🎉 (I loved that that word was a working example!)
